spring.application.name=Placement_Drive_Management
spring.datasource.url=
spring.datasource.username=postgres
spring.datasource.password=
server.port=8091
spring.jpa.hibernate.ddl-auto=update
app.jwt.secret=
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=604800000
