spring.application.name=Placement_Drive_Management
spring.datasource.url=jdbc:postgresql://localhost:5432/pdmsSS
spring.datasource.username=postgres
spring.datasource.password=postgresql123
server.port=8091
spring.jpa.hibernate.ddl-auto=update
app.jwt.secret=JWT-KEY-WHICH-SHOULD-BE-LARGE_THAT_SHOULDBE_32_CHARACTERS_LONG_VERY_LONG
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=604800000