spring.application.name=Placement_Drive_Management
spring.datasource.url=jdbc:postgresql://localhost:5432/pdms
spring.datasource.username=postgres
spring.datasource.password=postgresql123
server.port=8090
spring.jpa.hibernate.ddl-auto=update